---
title: "Prac6 Detecting Spatial Patterns"
author: "dnkimani"
date: "2024-11-12"
output: html_document
---
```{r Packages}
# loading packages
#first library a few packages that we will use during the practical
#note you may need to install them first...
library(tidyverse)
library(spatstat)
library(here)
library(sp)
library(tmap)
library(sf)
library(tmaptools)
```

```{r Loading & Checking London Bouroughs}
#First, get the London Borough Boundaries
LondonBoroughs <- st_read(here::here("Prac6_data", "statistical-gis-boundaries-london", "ESRI", "London_Borough_Excluding_MHW.shp"))

BoroughMap <- LondonBoroughs %>%
  dplyr::filter(str_detect(GSS_CODE, "^E09"))%>%
  st_transform(., 27700)

qtm(BoroughMap)
```

```{r Loading Blue Plaques}
# reading in the blue plaques data from web or geojson file
#Now get the location of all Blue Plaques in the City
#BluePlaques <- st_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson")

BluePlaques <- st_read(here::here("prac6_data",
                                  "open-plaques-london-2018-04-08.geojson")) %>%
  st_transform(.,27700)

summary(BluePlaques)
```

```{r Quick check of Loaded Data}
#plot the blue plaques in the city
tmap_mode("plot")
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaques) +
  tm_dots(col = "blue")
```

```{r Data Cleaning}
# notice above, points falling beyond the boundaries.
# we also need to remove duplicate points which might also cause issues with the analysis
# library(tidyverse)
#library(sf)
BluePlaques <- distinct(BluePlaques)
```

```{r Spatial Subsetting}
# only selecting the points inside london
# the second operator[LB, ] controls which attributes are kept. We leave it blank to manipulate later with tidyverse
BluePlaquesSub <- BluePlaques[BoroughMap,]

#check to see that they've been removed
tmap_mode("plot")
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```

```{r}
# consider Topological relations between vector geometries in section 6.5.2

# add sparse=false to get the complete matrix.
intersect_indices <-st_intersects(BoroughMap, BluePlaques)

# also consider Spatial Clipping section 6.5.3
```

```{r Spatial Joining}
# addressed in Prac5
```

```{r Study Area Selection}
# we will extract one borough to simplify the analysis
#extract the borough of Harrow

# select by attribute
Harrow <- BoroughMap %>%
  filter(., NAME=="Harrow")

#Check to see that the correct borough has been pulled out
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5)
```

```{r Spatial Clipping 2}
#clip the data to our single borough
BluePlaquesSub <- BluePlaques[Harrow,]
#check that it's worked
tmap_mode("plot") # tmap mode set to plotting
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```

```{r Setting Observation Window}
# Setting an observation window for spatstat to carry out the analysis
#now set a window as the borough boundary
window <- as.owin(Harrow)
plot(window)
```

```{r PPP Creation}
# spatstat does not work with sp or sf objects
# it only works with ppp objects, lets create one

#create a sp object
BluePlaquesSub<- BluePlaquesSub %>%
  as(., 'Spatial')
#create a ppp object
BluePlaquesSub.ppp <- ppp(x=BluePlaquesSub@coords[,1],
                          y=BluePlaquesSub@coords[,2],
                          window=window)

```

```{r}
# lets have a look at the new ppp object
BluePlaquesSub.ppp %>%
  plot(.,pch=16,cex=0.5, 
       main="Blue Plaques Harrow")
```

